<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');
/**
 * This a base controller that can be used when we need to send and ajax answer
 * to the browser. This default impementation of for send the anser in JSON.
 *
 * This class doesnt use the MY_ convention because its loaded using the PHP5
 * autoload feature , the code its appended to application config.php as
 * function __autoload($class)
 * {
 *    if(strstr($class,'_Controller'))
 *    {
 *       include_once(APPPATH . 'libraries/' . $class . EXT);
 *    }
 * }
 *
 * NOTES : Only for PHP%
 *
 * @author Carlos Arana Reategui
 * @version 1.00 , 28 JUN 2009
 *
 */
class Lib_Ajax_Controller extends Controller {

/**
 * Constructor
 */
    function  __construct() {
        parent::Controller();
    }


    /**
     * Helper method to generate the ajax answer , the format of the answer in this default
     * implementation is in JSON format, if we need in other format like XML this method and
     * _process_ajax_data()  need to ne override.
     * The answer will have the format :
     * {success: boolean,
     *  msg: { txt: 'a message string',
     *        code: a numeric identifier of the message (1 means the errors are field errors)
     *  },
     *  errors : {'field_name': 'flderror'},
     *  data :{no specific specification each controller will setup this vale overriding _process_ajax_data()}
     * }
     *
     *
     * IMPORTANT : If the fldlabels param its noy null , the caller need to be loaded previously
     * the lang stuff of the form and the form validation library that process the validation.
     *
     * @access protected
     * @param sucess , true or false.
     * @param msg_code , a numeric identifier of the msg.
     * @param msg_txt , the message string.
     * @param fieldlabels , An array of the form field labels, this array can be a simple array like
     * ('label1','label1','label1') or a complex one that contains the key field like the validation rules array.
     * @param extradata , mixed with some data need to be sended to browser , this will be processed
     * by _process_ajax_data() method.
     *
     * @return An string wiyh yhe JSON encoded answer.
     *
     * @uses the form validation CI libraries and the text helper functions, please
     * preload that stuff. Select your language previously for a correct localized messages.
     * The _process_ajax_extradata method.
     *
     */
    protected function _generate_ajax_answer($success=true,$msg_code=0,$msg_txt='',array $fldlabels=NULL,$extradata=NULL) {
        $this->load->helper('text');

        $result["success"] = $success;
        $result['msg']['txt'] =$msg_txt;
        $result['msg']['code'] =$msg_code;

        // If fldlabels its defined assume exist form field errors
        if ($fldlabels != NULL && isset ($fldlabels) && count($fldlabels) > 0) {
            $j=0;
            $count = count($fldlabels);
            for($i=0; $i < $count; $i++) {
            // get  the field  name
                if (is_array($fldlabels[$i])) {
                    $field = $fldlabels[$i]['field'];
                } else {
                    $field = $fldlabels[$i];
                }

                // Get the error message for the field
                $err_msg = $this->form_validation->error($field);
                // If exist a message , the fielld has an error
                if (strlen($err_msg) > 0) {

                    if ($j==0) {
                        $result['msg']['code'] =1;
                    }
                    // Get the translated human readable error and assign to the field id
                    $result['errors'][$field] =ascii_to_entities($err_msg);
                    $j++;
                }
                $field=NULL;
                $err_msg = NULL;
            }

        } else {
            $result['errors']['null'] =NULL;
        }

        if (isset ($extradata)) {
            $result['data'] = ascii_to_entities($this->_process_ajax_extradata($extradata));
        }
        
        $answer =  json_encode($result);
        $result = NULL;
        return $answer;
    }


    /**
     * Helper method that will be called by _generate_ajax_answer for process the extradata,
     * This need to br overriden by the specific controllers to manipulate the conversion, the
     * default implementation do noting and only return NULL.
     *
     * @access protected
     * @param data , data to ce processed.
     *
     * @return An string wiyh the JSON encoded answer.
     *
     */
    protected function _process_ajax_extradata($data) {
        return NULL;
    }


    /**
     * Helper method for process the answer in case that we need an to respond in a
     * way not supported by the expected standard generated by _generate_ajax_answer()
     * method.
     * for example  some GUI widgets only require a list of objects.
     * This method need to be overriden by the specific controllers to manipulate the conversion, the
     * default implementation do noting and only return NULL.
     *     
     * @access protected
     * @param data , data to be processed.
     *
     * @return An string wiyh the JSON encoded answer.
     *
     */
    protected function _generate_ajax_rawanswer($data) {
        return NULL;
    }

}

/* End of file ControllerBase.php */
/* Location: ./system/application/libraries/base/Lib_Ajax_Controller.php */
